t1.o: Question2b1.cpp
	g++ Question2b1.cpp -o t1.o 
	./t1.o

t2.o: Question2b2.cpp
	g++ Question2b2.cpp -o t2.o
	./t2.o

t3.o: Question2b3.cpp
	g++ Question2b3.cpp -o t3.o
	./t3.o

clear:
	rm *.o *.csv

all: Question2b1.cpp Question2b2.cpp Question2b3.cpp
	g++ Question2b1.cpp -o t1.o 
	./t1.o
	g++ Question2b2.cpp -o t2.o
	./t2.o
	g++ Question2b3.cpp -o t3.o
	./t3.o

